# Bank fraud detection

setup & load

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('/content/FraudShield_Banking_Data.csv')
df.head()

,Transaction_ID,Customer_ID,Transaction_Amount (in Million),Transaction_Time,Transaction_Date,Transaction_Type,Merchant_ID,Merchant_Category,Transaction_Location,Customer_Home_Location,...,Daily_Transaction_Count,Weekly_Transaction_Count,Avg_Transaction_Amount (in Million),Max_Transaction_Last_24h (in Million),Is_International_Transaction,Is_New_Merchant,Failed_Transaction_Count,Unusual_Time_Transaction,Previous_Fraud_Count,Fraud_Label
0,431438.0,24239.0,6.0,10:54,2025-03-08,POS,97028.0,ATM,Singapore,Lahore,...,4.0,17.0,2.0,4.0,Yes,Yes,0.0,No,1.0,Normal
1,902451.0,77250.0,9.0,19:23,2025-01-17,ATM,27515.0,ATM,Singapore,Lahore,...,4.0,9.0,5.0,8.0,Yes,Yes,1.0,No,1.0,Normal
2,223410.0,34294.0,3.0,10:20,2025-04-30,POS,13810.0,Electronics,Faisalabad,Faisalabad,...,5.0,18.0,5.0,8.0,Yes,No,0.0,Yes,1.0,Normal
3,145626.0,92041.0,1.0,14:11,2025-02-21,Online,10501.0,Grocery,London,Karachi,...,6.0,18.0,5.0,1.0,No,Yes,2.0,Yes,1.0,Normal
4,414637.0,71578.0,1.0,04:12,2025-04-11,Online,53569.0,Electronics,Singapore,Islamabad,...,3.0,18.0,4.0,3.0,No,Yes,1.0,No,1.0,Normal

In [7]:
df.shape

(46170, 25)

In [8]:
df.columns

Index(['Transaction_ID', 'Customer_ID', 'Transaction_Amount (in Million)',
       'Transaction_Time', 'Transaction_Date', 'Transaction_Type',
       'Merchant_ID', 'Merchant_Category', 'Transaction_Location',
       'Customer_Home_Location', 'Distance_From_Home', 'Device_ID',
       'IP_Address', 'Card_Type', 'Account_Balance (in Million)',
       'Daily_Transaction_Count', 'Weekly_Transaction_Count',
       'Avg_Transaction_Amount (in Million)',
       'Max_Transaction_Last_24h (in Million)', 'Is_International_Transaction',
       'Is_New_Merchant', 'Failed_Transaction_Count',
       'Unusual_Time_Transaction', 'Previous_Fraud_Count', 'Fraud_Label'],
      dtype='object')

*   **Transaction_ID**: A unique identifier for each transaction.
*   **Customer_ID**: A unique identifier for each customer.
*   **Transaction_Amount (in Million)**: The amount of the transaction, expressed in millions.
*   **Transaction_Time**: The time at which the transaction occurred.
*   **Transaction_Date**: The date on which the transaction occurred.
*   **Transaction_Type**: The type of transaction (e.g., POS, ATM, Online).
*   **Merchant_ID**: A unique identifier for the merchant involved in the transaction.
*   **Merchant_Category**: The category of the merchant (e.g., ATM, Electronics, Grocery).
*   **Transaction_Location**: The geographical location where the transaction took place.
*   **Customer_Home_Location**: The recorded home location of the customer.
*   **Distance_From_Home**: The distance between the transaction location and the customer's home location.
*   **Device_ID**: The identifier of the device used for the transaction.
*   **IP_Address**: The IP address associated with the transaction.
*   **Card_Type**: The type of card used for the transaction (e.g., Visa, MasterCard).
*   **Account_Balance (in Million)**: The customer's account balance, expressed in millions.
*   **Daily_Transaction_Count**: The number of transactions made by the customer within the last 24 hours.
*   **Weekly_Transaction_Count**: The number of transactions made by the customer within the last 7 days.
*   **Avg_Transaction_Amount (in Million)**: The average transaction amount for the customer.
*   **Max_Transaction_Last_24h (in Million)**: The maximum transaction amount made by the customer in the last 24 hours.
*   **Is_International_Transaction**: Indicates whether the transaction was international (Yes/No).
*   **Is_New_Merchant**: Indicates whether the merchant is new to the customer (Yes/No).
*   **Failed_Transaction_Count**: The number of failed transactions for the customer.
*   **Unusual_Time_Transaction**: Indicates whether the transaction occurred at an unusual time for the customer (Yes/No).
*   **Previous_Fraud_Count**: The count of previously detected fraudulent activities for the customer.
*   **Fraud_Label**: The target variable, indicating whether the transaction is 'Normal' or 'Fraud'.

In [10]:
display(df.describe())

,Transaction_ID,Customer_ID,Transaction_Amount (in Million),Merchant_ID,Distance_From_Home,Device_ID,Account_Balance (in Million),Daily_Transaction_Count,Weekly_Transaction_Count,Avg_Transaction_Amount (in Million),Max_Transaction_Last_24h (in Million),Failed_Transaction_Count,Previous_Fraud_Count
count,46168.000000,46161.000000,46162.000000,46164.000000,46168.000000,46160.000000,46160.000000,46160.000000,46164.000000,46161.000000,46165.000000,46158.000000,46167.000000
mean,550406.514924,54849.684127,5.004073,54937.590243,300.102279,552527.388800,21.012782,3.999372,12.526146,2.986395,5.017632,0.993501,0.500314
std,259440.617836,26089.819061,2.578829,25954.783018,172.836511,259985.923464,10.680272,2.001337,6.911928,1.413857,2.571833,0.816135,0.500005
min,100043.000000,10005.000000,1.000000,10001.000000,1.000000,100053.000000,3.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,324375.750000,32199.000000,3.000000,32591.000000,150.000000,327841.750000,12.000000,2.000000,7.000000,2.000000,3.000000,0.000000,0.000000
50%,552490.000000,54667.000000,5.000000,54890.000000,301.000000,553605.500000,21.000000,4.000000,13.000000,3.000000,5.000000,1.000000,1.000000
75%,775746.750000,77594.000000,7.000000,77263.250000,450.000000,779242.750000,30.000000,6.000000,18.000000,4.000000,7.000000,2.000000,1.000000
max,999992.000000,99996.000000,9.000000,99996.000000,599.000000,999989.000000,39.000000,7.000000,24.000000,5.000000,9.000000,2.000000,1.000000

In [11]:
missing_values = df.isnull().sum()
missing_values_exist = missing_values[missing_values > 0]
display(missing_values_exist)

Transaction_ID                            2
Customer_ID                               9
Transaction_Amount (in Million)           8
Transaction_Time                          9
Transaction_Date                          2
Transaction_Type                          4
Merchant_ID                               6
Merchant_Category                         9
Transaction_Location                      6
Customer_Home_Location                    4
Distance_From_Home                        2
Device_ID                                10
IP_Address                                7
Card_Type                                 4
Account_Balance (in Million)             10
Daily_Transaction_Count                  10
Weekly_Transaction_Count                  6
Avg_Transaction_Amount (in Million)       9
Max_Transaction_Last_24h (in Million)     5
Is_International_Transaction              5
Is_New_Merchant                           6
Failed_Transaction_Count                 12
Unusual_Time_Transaction                  4
Previous_Fraud_Count                      3
Fraud_Label                               5
dtype: int64

### Option 3: Imputer les valeurs manquantes
L'imputation consiste à remplacer les valeurs manquantes par des valeurs estimées. Les méthodes courantes incluent la moyenne, la médiane ou le mode pour les données numériques, et le mode ou une catégorie 'inconnue' pour les données catégorielles.

**Quand l'utiliser?**
*   Lorsque la suppression de lignes ou de colonnes entraînerait une perte de données trop importante.
*   Lorsque les valeurs manquantes sont réparties de manière aléatoire et ne sont pas indicatives d'un problème sous-jacent avec la collecte de données.

#### Imputation pour les colonnes numériques (Moyenne ou Médiane)

In [14]:
# Créer une copie
df_imputed_numeric = df.copy()

# Identifier les colonnes numériques avec des valeurs manquantes
numeric_cols_with_na = df_imputed_numeric.select_dtypes(include=np.number).columns
numeric_cols_with_na = [col for col in numeric_cols_with_na if df_imputed_numeric[col].isnull().any()]

for col in numeric_cols_with_na:
    # Vous pouvez choisir d'utiliser la moyenne (mean()) ou la médiane (median())
    df_imputed_numeric[col].fillna(df_imputed_numeric[col].median(), inplace=True)

print("Valeurs manquantes après imputation numérique (médiane):")
display(df_imputed_numeric[numeric_cols_with_na].isnull().sum())

Valeurs manquantes après imputation numérique (médiane):

/tmp/ipykernel_455/3423496428.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_imputed_numeric[col].fillna(df_imputed_numeric[col].median(), inplace=True)

Transaction_ID                           0
Customer_ID                              0
Transaction_Amount (in Million)          0
Merchant_ID                              0
Distance_From_Home                       0
Device_ID                                0
Account_Balance (in Million)             0
Daily_Transaction_Count                  0
Weekly_Transaction_Count                 0
Avg_Transaction_Amount (in Million)      0
Max_Transaction_Last_24h (in Million)    0
Failed_Transaction_Count                 0
Previous_Fraud_Count                     0
dtype: int64

#### Imputation pour les colonnes catégorielles (Mode ou 'Inconnu')

In [15]:
# Créer une copie
df_imputed_categorical = df_imputed_numeric.copy() # On continue avec le df où les valeurs numériques ont déjà été imputées

# Identifier les colonnes catégorielles avec des valeurs manquantes
categorical_cols_with_na = df_imputed_categorical.select_dtypes(include='object').columns
categorical_cols_with_na = [col for col in categorical_cols_with_na if df_imputed_categorical[col].isnull().any()]

for col in categorical_cols_with_na:
    # Option 1: Remplacer par le mode (valeur la plus fréquente)
    df_imputed_categorical[col].fillna(df_imputed_categorical[col].mode()[0], inplace=True)
    # Option 2: Remplacer par une nouvelle catégorie 'Inconnu'
    # df_imputed_categorical[col].fillna('Inconnu', inplace=True)

print("Valeurs manquantes après imputation catégorielle (mode):")
display(df_imputed_categorical[categorical_cols_with_na].isnull().sum())

Valeurs manquantes après imputation catégorielle (mode):

/tmp/ipykernel_455/1711058535.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_imputed_categorical[col].fillna(df_imputed_categorical[col].mode()[0], inplace=True)

Transaction_Time                0
Transaction_Date                0
Transaction_Type                0
Merchant_Category               0
Transaction_Location            0
Customer_Home_Location          0
IP_Address                      0
Card_Type                       0
Is_International_Transaction    0
Is_New_Merchant                 0
Unusual_Time_Transaction        0
Fraud_Label                     0
dtype: int64

In [16]:
df_imputed = df_imputed_categorical.copy()
df_imputed.head()

,Transaction_ID,Customer_ID,Transaction_Amount (in Million),Transaction_Time,Transaction_Date,Transaction_Type,Merchant_ID,Merchant_Category,Transaction_Location,Customer_Home_Location,...,Daily_Transaction_Count,Weekly_Transaction_Count,Avg_Transaction_Amount (in Million),Max_Transaction_Last_24h (in Million),Is_International_Transaction,Is_New_Merchant,Failed_Transaction_Count,Unusual_Time_Transaction,Previous_Fraud_Count,Fraud_Label
0,431438.0,24239.0,6.0,10:54,2025-03-08,POS,97028.0,ATM,Singapore,Lahore,...,4.0,17.0,2.0,4.0,Yes,Yes,0.0,No,1.0,Normal
1,902451.0,77250.0,9.0,19:23,2025-01-17,ATM,27515.0,ATM,Singapore,Lahore,...,4.0,9.0,5.0,8.0,Yes,Yes,1.0,No,1.0,Normal
2,223410.0,34294.0,3.0,10:20,2025-04-30,POS,13810.0,Electronics,Faisalabad,Faisalabad,...,5.0,18.0,5.0,8.0,Yes,No,0.0,Yes,1.0,Normal
3,145626.0,92041.0,1.0,14:11,2025-02-21,Online,10501.0,Grocery,London,Karachi,...,6.0,18.0,5.0,1.0,No,Yes,2.0,Yes,1.0,Normal
4,414637.0,71578.0,1.0,04:12,2025-04-11,Online,53569.0,Electronics,Singapore,Islamabad,...,3.0,18.0,4.0,3.0,No,Yes,1.0,No,1.0,Normal

In [17]:
missing_values = df_imputed.isnull().sum()
missing_values_exist = missing_values[missing_values > 0]
display(missing_values_exist)

Series([], dtype: int64)